"""Add unique constraint to Progress table to prevent duplicate entries

Revision ID: d1cb1933e245
Revises: f497e14d2b3c
Create Date: 2025-06-30 01:07:29.222480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cb1933e245'
down_revision = 'f497e14d2b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_video_progress', ['user_id', 'video_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_video_progress', type_='unique')

    # ### end Alembic commands ###
